name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17  # JDK 17로 변경
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # JDK 17으로 변경
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean build
          # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
        
    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

    - name: Make zip file
      run: zip -r ./coinTalk.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

  # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./coinTalk.zip s3://git-test-s3-custom

      # Deploy
    - name: Deploy
      run: |
        aws deploy create-deployment \
        --application-name git-test-code \
        --deployment-config-name CodeDeployDefault.AllAtOnce \
        --deployment-group-name git-test-code \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=git-test-s3-custom,bundleType=zip,key=coinTalk.zip \
        --region ap-northeast-2 \
      
